---
title: "year1 reflection"
author: "Fauzan Lodhi"
date: "2025-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About Me)

Name: Fauzan Lodhi
Program: Honours Mathematics (Statistics, Co-op)
Sport: Men's Basketball

## Year 1 Projects)


### Player scouting cards

Initially created player scouting cards in Power BI.
Ran into access issues and was forced to pivot.
Will be deployed on a Shiny app in the future.

This included box score stats and synergy data,
which was cleaned and aggregated using Pandas.

This was entirely done between us and Coach
(e.g. no other IST streams).


### Pregame scouts

Combined player scouting numbers and team stats into pregame scouts.
These were sent to Coach every Sunday evening for all games
in the upcoming week.

This included box score stats and synergy data,
which was cleaned and aggregated using Pandas.

This was entirely done between us and Coach
(e.g. no other IST streams).


### Shot selection correlations

Coach tagged 100 shots with a number of variables and then labelled
shots based on selection (1-10). Variables included:
- who started the break?
- hit ahead?
- contested?
- etc.

Ran correlation numbers and reported back to him.

entirely done between us and Coach
(e.g. no other IST streams).


### Postgame reports

Compiled box score stats into postgame reports for coaches
and players to reflect. This included individual player stats
as well as team box score stats, pace, etc.


### RPE Analysis

This is an ongoing project with the sports science stream.
Trying to identify trends in player ``Rated Perceived Exertion (RPE)''
before and after practices, daily. The end goal is to help coaches
optimize practice plans and maximize athlete wellness and engagement.


## Overall Experience

Overall I enjoyed my first year with the team. It took some time to get things
rolling and at times both we and the coaches were unsure of our roles,
how involved we needed to be, and how to improve our work.

In the Fall, we were less engaged and operated in the background. However,
in the Winter I was much more involved with the team, going to practices and
games to connect with coaches, athletes, and trainers.
The added engagement and interaction not only boosted productivity but also
allowed us to understand the team better and identify ways to tailor
our projects to their needs. 


### What went well?

- Coaches showed excitement for the program
- Team was great to be around
- David, Rithika & data solutions team were extremely supportive throughout
the season and made things much easier


### What needs to improve?
- Read, read, read.
- More formal IST meetings with all streams (already on the table)
- \bf{I} need to be more creative. 

